### ISSUE TITLE
What custom features you guys will attempt to implement?

### ISSUE THREAD

**Issue by scalalang2** [sei-protocol/sei-tendermint#18]
Hi, I'm a software engineer and one of fans on sei protocol.
And I came here with just curiosity for what you guys to do with tendermint core.

I want to know what custom features will be enabled in the future.

**Comment by philipsu522** [comment]
Hey! Feel free to take a look at our whitepaper for more info! https://github.com/sei-protocol/sei-chain/blob/master/whitepaper/Sei_Whitepaper.pdf
