### ISSUE TITLE
Transaction Decoding Error Using @cosmjs

### ISSUE THREAD

**Issue by blorgon1** [sei-protocol/sei-tendermint#93]
When using the `@cosmjs` library to query Sei, transaction response decoding fails due to the `proof` field not being formatted as expected.

I've opened https://github.com/cosmos/cosmjs/issues/1391 to address this but ~~it seems that other Tendermint v0.35+ backends do not have this issue so I suspect it's related to some changes in this fork~~ `@cosmjs` does not plan to support Tendermint v0.35, and will only support Tendermint v0.37. Are there any plans to incorporate the v0.37 changes into this fork? Or at least can the transaction response proof be fixed to match what is expected?

**Comment by besated** [comment]
Hey! Thanks for bringing this up - this is a known issue that we're looking into. We're planning to make changes to revert some of the TM v0.35 changes to make it compatible with TM v0.34 in a future upgrade. 

In the meantime, we have published a custom version of the `Stargate` and `CosmWasm` clients in our `@sei-js` package that is compatible with our TM version here - https://github.com/sei-protocol/sei-js/blob/f304de5b1169c1e33f732548a1fbef3c427343cb/packages/core/src/lib/signingClient/stargateClient.ts#L21
